title:             Cho-Nan's essays on tech 
description:       Lessons in tech that make us a better team
author:            Cho-Nan Tsai
baseurl:           ""
url:               "http://xxx.github.io"

# Social Profiles
twitter_username:  chonantsai

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
